name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World!"
          echo "What is your name?"
          echo "Never mind!"
      - name: Print GoodBye
        run: echo "Done~ Bye!"
